vich_uploader:
    db_driver: orm
    mappings:
        personne_avatar:
            uri_prefix: "%app.path.personne_avatar%"
            upload_destination: "%kernel.project_dir%/public%app.path.personne_avatar%"
    #namer: Vich\UploaderBundle\Naming\UniqidNamer
    #delete_on_remove: true
    #delete_on_update: true
